# -*- coding: utf-8 -*-
"""Reastaurant_reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKZiJqaIz3WzplVvRuGxRi7JC-Bnw567
"""

# Importing Libraries
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

# Import dataset
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter = '\t')

import re

import nltk

nltk.download('stopwords')

# to remove stopword
from nltk.corpus import stopwords

# for Stemming propose
from nltk.stem.porter import PorterStemmer

# cleaning the reviews
corpus = []

# 1000 (reviews) rows to clean
for i in range(0, 1000):

	review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])

	review = review.lower()

  #tokenizing the review by words
	review = review.split()

	ps = PorterStemmer()

	review = [ps.stem(word) for word in review
				if not word in set(stopwords.words('english'))]

	review = ' '.join(review)

  #creating a corpus
	corpus.append(review)

corpus[:1500]

# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 1500)

X = cv.fit_transform(corpus).toarray()

y = dataset.iloc[:, 1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

# Fitting Random Forest Classification
# to the Training set
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 501,
							criterion = 'entropy')

model.fit(X_train, y_train)

# Predicting the Test set results
y_pred = model.predict(X_test)

y_pred

#Checking Accuracy
acc= round(model.score(X_test,y_test)*100,2)
print(str(acc)+'%')

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

cm